name: release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16.9.0
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
        env:
          NODE_ENV: production
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload index.js
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/index.js
          asset_name: index.js
          asset_content_type: text/javascript
      - name: Update README.md
        id: update-readme
        run: yarn update-readme
      - name: Commit README.md if changed
        id: commit-readme
        run: |-
          git diff
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          git commit -m "Updated README" -a || exit 0
          git switch -c tmp
          git branch
          git switch main
          git merge tmp
          git push origin main
          git branch -d tmp
